site_name: Catálogo de Padrões de Requisitos de Segurança para Internet das Coisas (IoT)
site_author: Higor, Enersto
site_description: Catálogo de Padrões de Requisitos de Segurança para IoT, cobrindo as categorias STRIDE e considerando as restrições particulares desse ambiente.

nav:
  - Sobre: index.md
  - STRIDE:
    - Spoofing: _strides/spoofing.md
    - Tampering: _strides/tampering.md
    - Repudiation: _strides/repudiation.md
    - Information Disclosure: _strides/information_disclosure.md
    - Denial of Service: _strides/denial_of_service.md
    - Elevation of Privilege: _strides/elevation_of_privilege.md

plugins:
  - search

theme:
  name: material
  features:
    - navigation.expand
    - navigation.sections
    - navigation.top
    - header.autohide

  palette:
    - scheme: default
      primary: purple
      toggle:
        icon: material/weather-night
        name: Modo noturno
    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/weather-sunny
        name: Modo claro


markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.tasklist  # Lista de tarefas
  - pymdownx.emoji  # Emojis
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: pymdownx.superfences.fence_div_format

extra_css:
  - https://unpkg.com/mermaid@8.5.1/dist/mermaid.css
  - stylesheets/extra.css
extra_javascript:
  - https://unpkg.com/mermaid@8.5.1/dist/mermaid.min.js
  - javascripts/cvss.js